#Docker Compose : Prometheus + Grafana + Alertmanager + Node Exporter
#Gnetw

version: '3.5'

networks:
    traefik:
        name: traefik
    back: 
        name: back
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: always
        networks:
        - back
        - traefik
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/rules:/etc/prometheus/rules
        - ./prometheus/db:/prometheus
        command:
        - --web.enable-admin-api
        - --config.file=/etc/prometheus/prometheus.yml
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.middlewares=pageauth@file"
        - "traefik.http.routers.prometheus.rule=Host(`prom.labo.local`)"
        - "traefik.http.routers.prometheus.entryPoints=https"
        - "traefik.http.routers.prometheus.tls=true"
        - "traefik.http.routers.prometheus.service=prometheus"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

    grafana:
        image: grafana/grafana
        depends_on:
        - prometheus
        container_name: grafana
        restart: always
        user: '1000'
        networks:
        - back
        - traefik
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
        - ./grafana/log:/var/log/grafana
        - ./grafana/data:/var/lib/grafana
        - ./grafana/grafana.ini:/etc/grafana/grafana.ini
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.graf.rule=Host(`graf.labo.local`)"
        - "traefik.http.routers.graf.entryPoints=https"
        - "traefik.http.routers.graf.tls=true"
        - "traefik.http.routers.graf.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        depends_on:
        - prometheus
        volumes:
        - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        - ./alertmanager/data:/data
        command:
        - '--config.file=/etc/alertmanager/alertmanager.yml'
        - '--storage.path=/data'
        networks:
        - back
        - traefik
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.labo.local`)"
        - "traefik.http.routers.alertmanager.entryPoints=https"
        - "traefik.http.routers.alertmanager.tls=true"
        - "traefik.http.routers.alertmanager.service=alertmanager"
        - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"

    nodeexporter:
        image: prom/node-exporter
        container_name: nodeexporter
        restart: always
        ports:
        - 9100:9100
        networks:
        - back
        volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
